//! Builds NBT blobs from `assets/<version>/<registry>/<entry>.json` and
//! generates a Rust module that includes them via `include_bytes!`.
//!
//! The generated module is included from `src/lib.rs`.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use serde_json::{Map, Value};
use ussr_nbt::owned::{Compound, List, Nbt, Tag};

/// All supported (version, registry_id, asset subpath) tuples. The asset path
/// is the directory under `assets/<version>/` containing per-entry JSONs.
const VERSIONS: &[&str] = &["26.1.2"];

/// Registries we ship per version, in (registry_id, asset_subpath) form.
const REGISTRIES: &[(&str, &str)] = &[
    ("minecraft:damage_type", "damage_type"),
    ("minecraft:dimension_type", "dimension_type"),
    ("minecraft:painting_variant", "painting_variant"),
    ("minecraft:worldgen/biome", "worldgen/biome"),
    ("minecraft:cat_variant", "cat_variant"),
    ("minecraft:cat_sound_variant", "cat_sound_variant"),
    ("minecraft:chicken_variant", "chicken_variant"),
    ("minecraft:chicken_sound_variant", "chicken_sound_variant"),
    ("minecraft:cow_variant", "cow_variant"),
    ("minecraft:cow_sound_variant", "cow_sound_variant"),
    ("minecraft:frog_variant", "frog_variant"),
    ("minecraft:pig_variant", "pig_variant"),
    ("minecraft:pig_sound_variant", "pig_sound_variant"),
    ("minecraft:wolf_variant", "wolf_variant"),
    ("minecraft:wolf_sound_variant", "wolf_sound_variant"),
    (
        "minecraft:zombie_nautilus_variant",
        "zombie_nautilus_variant",
    ),
    ("minecraft:timeline", "timeline"),
    ("minecraft:world_clock", "world_clock"),
    ("minecraft:trim_material", "trim_material"),
    ("minecraft:trim_pattern", "trim_pattern"),
    ("minecraft:banner_pattern", "banner_pattern"),
    ("minecraft:instrument", "instrument"),
    ("minecraft:chat_type", "chat_type"),
    ("minecraft:jukebox_song", "jukebox_song"),
    // TODO(enchantment-registry): ship `minecraft:enchantment` properly. The
    // Mojang enchantment codec is highly polymorphic (tagged unions on
    // `type`, level-based values, predicate trees) and the generic JSON→NBT
    // walker produces NBT that fails codec validation on 42/43 vanilla
    // entries. Options to revisit later:
    //   1. Add per-field schema overrides for enchantment subtrees.
    //   2. Hand-write a dedicated JSON→NBT path for this registry.
    //   3. Pre-bake the NBT blobs from a vanilla server's network capture.
    // Until then we omit it; the client falls back to its built-in data.
];

/// Tag namespaces shipped per version, in (registry_id, tag_subpath) form. The
/// tag JSONs live under `assets/<version>/<tag_subpath>/...` and each tag id
/// is the path under that subpath, prefixed with `minecraft:`.
const TAG_REGISTRIES: &[(&str, &str)] = &[
    ("minecraft:damage_type", "tags/damage_type"),
    ("minecraft:painting_variant", "tags/painting_variant"),
    ("minecraft:timeline", "tags/timeline"),
    ("minecraft:worldgen/biome", "tags/worldgen/biome"),
    ("minecraft:banner_pattern", "tags/banner_pattern"),
    ("minecraft:instrument", "tags/instrument"),
    // tags/enchantment skipped because the registry itself is not shipped.
];

fn main() {
    println!("cargo:rerun-if-changed=assets");
    println!("cargo:rerun-if-changed=build.rs");

    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    let nbt_root = out_dir.join("nbt");

    let mut codegen = String::new();
    codegen.push_str("// @generated by build.rs — do not edit\n\n");
    codegen.push_str("pub static REGISTRIES: &[(&str, &[(&str, &[(&str, &[u8])])])] = &[\n");

    for version in VERSIONS {
        codegen.push_str(&format!("    ({version:?}, &[\n"));
        for (registry_id, subpath) in REGISTRIES {
            let src_dir = crate_dir.join("assets").join(version).join(subpath);
            if !src_dir.is_dir() {
                panic!("missing asset directory: {}", src_dir.display());
            }

            let mut entries: BTreeMap<String, PathBuf> = BTreeMap::new();
            collect_jsons(&src_dir, &src_dir, &mut entries);

            codegen.push_str(&format!("        ({registry_id:?}, &[\n"));
            for (entry_id, json_path) in &entries {
                let json_text = fs::read_to_string(json_path)
                    .unwrap_or_else(|e| panic!("read {}: {e}", json_path.display()));
                let value: Value = serde_json::from_str(&json_text)
                    .unwrap_or_else(|e| panic!("parse {}: {e}", json_path.display()));

                let nbt = json_to_nbt(&value, registry_id);

                let nbt_rel = Path::new("nbt")
                    .join(version)
                    .join(subpath)
                    .join(format!("{entry_id}.nbt"));
                let nbt_path = out_dir.join(&nbt_rel);
                fs::create_dir_all(nbt_path.parent().unwrap()).unwrap();

                let mut buf = Vec::new();
                nbt.write(&mut buf).unwrap();
                let mut f = fs::File::create(&nbt_path).unwrap();
                f.write_all(&buf).unwrap();

                let full_id = format!("minecraft:{entry_id}");
                let include_path = nbt_rel.to_string_lossy().replace('\\', "/");
                codegen.push_str(&format!(
                    "            ({full_id:?}, include_bytes!({include_path:?})),\n"
                ));
            }
            codegen.push_str("        ]),\n");
        }
        codegen.push_str("    ]),\n");
    }

    codegen.push_str("];\n\n");

    // ---- TAGS static -----------------------------------------------------
    codegen.push_str("pub static TAGS: &[(&str, &[(&str, &[(&str, &[&str])])])] = &[\n");
    for version in VERSIONS {
        let _ = writeln!(codegen, "    ({version:?}, &[");
        for (registry_id, subpath) in TAG_REGISTRIES {
            let src_dir = crate_dir.join("assets").join(version).join(subpath);
            if !src_dir.is_dir() {
                continue;
            }

            let mut raw: BTreeMap<String, Vec<String>> = BTreeMap::new();
            let mut paths: BTreeMap<String, PathBuf> = BTreeMap::new();
            collect_jsons(&src_dir, &src_dir, &mut paths);

            for (tag_short_id, json_path) in &paths {
                let json_text = fs::read_to_string(json_path)
                    .unwrap_or_else(|e| panic!("read {}: {e}", json_path.display()));
                let value: Value = serde_json::from_str(&json_text)
                    .unwrap_or_else(|e| panic!("parse {}: {e}", json_path.display()));
                let values = parse_tag_values(&value, json_path);
                let full_tag_id = format!("minecraft:{tag_short_id}");
                raw.insert(full_tag_id, values);
            }

            // Resolve `#tag` references recursively so the output contains
            // only direct entry IDs.
            let _ = writeln!(codegen, "        ({registry_id:?}, &[");
            for tag_id in raw.keys() {
                let resolved = resolve_tag(tag_id, &raw, &mut HashSet::new());
                let _ = write!(codegen, "            ({tag_id:?}, &[");
                for (i, entry_id) in resolved.iter().enumerate() {
                    if i > 0 {
                        codegen.push_str(", ");
                    }
                    let _ = write!(codegen, "{entry_id:?}");
                }
                codegen.push_str("]),\n");
            }
            codegen.push_str("        ]),\n");
        }
        codegen.push_str("    ]),\n");
    }
    codegen.push_str("];\n");

    let out_file = out_dir.join("registries.rs");
    fs::write(&out_file, codegen).unwrap();

    drop(nbt_root);

    // ---- BLOCKS codegen --------------------------------------------------
    let mut blocks_code = String::new();
    blocks_code.push_str("// @generated by build.rs — do not edit\n\n");
    for version in VERSIONS {
        let blocks_path = crate_dir.join("assets").join(version).join("blocks.json");
        if !blocks_path.is_file() {
            continue;
        }
        let shapes_path = crate_dir
            .join("assets")
            .join(version)
            .join("blockCollisionShapes.json");
        let shapes_value = if shapes_path.is_file() {
            let txt = fs::read_to_string(&shapes_path)
                .unwrap_or_else(|e| panic!("read {}: {e}", shapes_path.display()));
            Some(serde_json::from_str::<Value>(&txt).expect("parse blockCollisionShapes.json"))
        } else {
            None
        };
        let txt = fs::read_to_string(&blocks_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", blocks_path.display()));
        let blocks_json: Value = serde_json::from_str(&txt).expect("parse blocks.json");
        emit_blocks_module(
            &mut blocks_code,
            version,
            &blocks_json,
            shapes_value.as_ref(),
        );
    }
    fs::write(out_dir.join("blocks.rs"), blocks_code).unwrap();
}

// =============================================================================
// Blocks codegen
// =============================================================================

#[derive(Debug, Clone)]
enum PropKind {
    Bool,
    /// Numeric range — values are `0..=max`. Stored as `u8`.
    Int {
        max: u8,
    },
    /// Enum with named variants. `enum_name` is the deduplicated Rust ident.
    Enum {
        enum_name: String,
        values: Vec<String>,
    },
}

#[derive(Debug, Clone)]
struct Property {
    name: String,
    kind: PropKind,
}

#[derive(Debug, Clone)]
struct BlockDef {
    /// `minecraft:foo`.
    full_name: String,
    /// PascalCase Rust type name (e.g. `OakStairs`).
    rust_type: String,
    /// SCREAMING_SNAKE_CASE Rust ident (e.g. `OAK_STAIRS`).
    rust_const: String,
    properties: Vec<Property>,
    /// Smallest state id (states[0]).
    min_state_id: i32,
    /// Largest state id (states[-1]).
    max_state_id: i32,
    /// Default state id (the `"default": true` entry, or `min_state_id`).
    default_state_id: i32,
    /// Per-state shape id, indexed by `state_id - min_state_id`. `None` means
    /// the prismarine vendored data has no entry for this block.
    shape_per_state: Option<Vec<u32>>,
}

fn emit_blocks_module(
    out: &mut String,
    version: &str,
    blocks_json: &Value,
    shapes_json: Option<&Value>,
) {
    let blocks_obj = blocks_json
        .as_object()
        .expect("blocks.json root must be object");

    // Pass 1: collect every (property name, value-set) pair so we can pick
    // unique enum names before emitting structs.
    let mut variants: BTreeMap<String, BTreeMap<Vec<String>, ()>> = BTreeMap::new();
    for (_, block) in blocks_obj.iter() {
        let Some(props) = block.get("properties").and_then(|v| v.as_object()) else {
            continue;
        };
        for (pname, vals) in props {
            let values = json_string_array(vals);
            if classify_values(&values).is_enum_like() {
                variants
                    .entry(pname.clone())
                    .or_default()
                    .insert(values, ());
            }
        }
    }

    // Assign enum names: `PascalName` if unique; else suffix with cardinality
    // when sufficient; else suffix with the first value.
    let mut enum_names: BTreeMap<(String, Vec<String>), String> = BTreeMap::new();
    for (name, sets) in &variants {
        let pascal = pascal_case(name);
        if sets.len() == 1 {
            enum_names.insert((name.clone(), sets.keys().next().unwrap().clone()), pascal);
            continue;
        }
        // Group by cardinality.
        let mut by_card: BTreeMap<usize, Vec<&Vec<String>>> = BTreeMap::new();
        for vs in sets.keys() {
            by_card.entry(vs.len()).or_default().push(vs);
        }
        for (card, list) in &by_card {
            if list.len() == 1 {
                let nm = format!("{pascal}{card}");
                enum_names.insert((name.clone(), list[0].clone()), nm);
            } else {
                for vs in list {
                    let suffix = pascal_case(&vs[0]);
                    let nm = format!("{pascal}{card}{suffix}");
                    enum_names.insert((name.clone(), (*vs).clone()), nm);
                }
            }
        }
    }

    // Build per-block defs with resolved property kinds.
    let mut defs: Vec<BlockDef> = Vec::new();
    for (full_name, block) in blocks_obj.iter() {
        let short = full_name
            .strip_prefix("minecraft:")
            .unwrap_or(full_name.as_str());
        let rust_type = pascal_case(short);
        let rust_const = short.to_ascii_uppercase();

        let states_arr = block
            .get("states")
            .and_then(|v| v.as_array())
            .expect("block states");
        let min_state_id = states_arr[0].get("id").and_then(|v| v.as_i64()).unwrap() as i32;
        let max_state_id = states_arr
            .last()
            .unwrap()
            .get("id")
            .and_then(|v| v.as_i64())
            .unwrap() as i32;
        let default_state_id = states_arr
            .iter()
            .find(|s| s.get("default").and_then(|v| v.as_bool()).unwrap_or(false))
            .and_then(|s| s.get("id").and_then(|v| v.as_i64()))
            .map(|n| n as i32)
            .unwrap_or(min_state_id);

        let mut properties = Vec::new();
        if let Some(props_obj) = block.get("properties").and_then(|v| v.as_object()) {
            for (pname, vals) in props_obj {
                let values = json_string_array(vals);
                let kind = match classify_values(&values) {
                    ValueClass::Bool => PropKind::Bool,
                    ValueClass::Int { max } => PropKind::Int { max },
                    ValueClass::Enum => {
                        let nm = enum_names
                            .get(&(pname.clone(), values.clone()))
                            .cloned()
                            .expect("enum name assigned");
                        PropKind::Enum {
                            enum_name: nm,
                            values: values.clone(),
                        }
                    }
                };
                properties.push(Property {
                    name: pname.clone(),
                    kind,
                });
            }
        }

        // Pull per-state shape ids from prismarine, if present.
        let shape_per_state = shapes_json
            .and_then(|j| j.get("blocks"))
            .and_then(|b| b.get(short))
            .map(|val| match val {
                Value::Number(n) => {
                    let id = n.as_u64().expect("shape id u64") as u32;
                    let count = (max_state_id - min_state_id + 1) as usize;
                    vec![id; count]
                }
                Value::Array(arr) => arr
                    .iter()
                    .map(|v| v.as_u64().expect("shape id u64") as u32)
                    .collect(),
                _ => Vec::new(),
            })
            .filter(|v| !v.is_empty());

        defs.push(BlockDef {
            full_name: full_name.clone(),
            rust_type,
            rust_const,
            properties,
            min_state_id,
            max_state_id,
            default_state_id,
            shape_per_state,
        });
    }

    // Sort blocks for deterministic output.
    defs.sort_by(|a, b| a.full_name.cmp(&b.full_name));

    let mod_ident = format!("v{}", version.replace('.', "_"));
    let _ = writeln!(
        out,
        "/// Generated block data for vanilla Minecraft {version}."
    );
    let _ = writeln!(
        out,
        "#[allow(clippy::identity_op, clippy::erasing_op, clippy::eq_op, dead_code)]"
    );
    let _ = writeln!(out, "pub mod {mod_ident} {{");

    // ---- props module
    let _ = writeln!(out, "    /// Property enums shared across blocks.");
    let _ = writeln!(out, "    pub mod props {{");
    // Collect enums by their unique rust name.
    let mut emitted: BTreeSet<String> = BTreeSet::new();
    for def in &defs {
        for p in &def.properties {
            if let PropKind::Enum { enum_name, values } = &p.kind {
                if !emitted.insert(enum_name.clone()) {
                    continue;
                }
                let _ = writeln!(
                    out,
                    "        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"
                );
                let _ = writeln!(out, "        #[repr(u8)]");
                let _ = writeln!(out, "        pub enum {enum_name} {{");
                for (i, v) in values.iter().enumerate() {
                    let _ = writeln!(out, "            {} = {i},", pascal_case(v));
                }
                let _ = writeln!(out, "        }}");
                let _ = writeln!(out, "        impl {enum_name} {{");
                let _ = writeln!(
                    out,
                    "            #[inline] pub const fn from_index(i: u32) -> Option<Self> {{"
                );
                let _ = writeln!(out, "                match i {{");
                for (i, v) in values.iter().enumerate() {
                    let _ = writeln!(
                        out,
                        "                    {i} => Some(Self::{}),",
                        pascal_case(v)
                    );
                }
                let _ = writeln!(out, "                    _ => None,");
                let _ = writeln!(out, "                }}");
                let _ = writeln!(out, "            }}");
                let _ = writeln!(out, "        }}");
            }
        }
    }
    let _ = writeln!(out, "    }}");

    // ---- blocks module: const default state ids
    let _ = writeln!(out, "    /// Default block-state id for each block.");
    let _ = writeln!(out, "    pub mod blocks {{");
    for def in &defs {
        let _ = writeln!(
            out,
            "        /// `{}`. State range: `{}..={}`.",
            def.full_name, def.min_state_id, def.max_state_id
        );
        let _ = writeln!(
            out,
            "        pub const {}: i32 = {};",
            def.rust_const, def.default_state_id
        );
    }
    let _ = writeln!(out, "    }}");

    // ---- state module: typed structs per stateful block
    let _ = writeln!(out, "    /// Typed wrappers for blocks with properties.");
    let _ = writeln!(out, "    pub mod state {{");
    let _ = writeln!(out, "        #[allow(unused_imports)] use super::props::*;");
    for def in &defs {
        if def.properties.is_empty() {
            continue;
        }
        emit_state_struct(out, def);
    }
    let _ = writeln!(out, "    }}");

    // ---- shapes module
    if let Some(shapes) = shapes_json {
        emit_shapes_module(out, &defs, shapes);
    }

    let _ = writeln!(out, "}}");
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ValueClass {
    Bool,
    Int { max: u8 },
    Enum,
}

impl ValueClass {
    fn is_enum_like(self) -> bool {
        matches!(self, ValueClass::Enum)
    }
}

fn classify_values(values: &[String]) -> ValueClass {
    // Bool: exactly the set {"true", "false"}.
    if values.len() == 2
        && values.iter().any(|v| v == "true")
        && values.iter().any(|v| v == "false")
    {
        return ValueClass::Bool;
    }
    // Int: every value parses as u32.
    if values.iter().all(|v| v.parse::<u32>().is_ok()) {
        let max = values
            .iter()
            .map(|v| v.parse::<u32>().unwrap())
            .max()
            .unwrap_or(0);
        return ValueClass::Int { max: max as u8 };
    }
    ValueClass::Enum
}

fn json_string_array(v: &Value) -> Vec<String> {
    v.as_array()
        .expect("property values array")
        .iter()
        .map(|x| x.as_str().expect("string value").to_string())
        .collect()
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for ch in s.chars() {
        if ch == '_' || ch == '/' || ch == '-' || ch == ':' {
            up = true;
        } else if up {
            out.extend(ch.to_uppercase());
            up = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn rust_keyword_safe(name: &str) -> String {
    // Property names like `type` clash with Rust keywords.
    const KW: &[&str] = &[
        "type", "ref", "move", "match", "loop", "for", "if", "else", "in", "let", "fn", "mod",
        "use", "where", "while", "true", "false", "self", "super", "crate",
    ];
    if KW.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn emit_state_struct(out: &mut String, def: &BlockDef) {
    let ty = &def.rust_type;
    // Compute strides — the rightmost property changes fastest, matching the
    // Mojang report's lexicographic state ordering.
    let cards: Vec<u32> = def
        .properties
        .iter()
        .map(|p| match &p.kind {
            PropKind::Bool => 2,
            PropKind::Int { max } => (*max as u32) + 1,
            PropKind::Enum { values, .. } => values.len() as u32,
        })
        .collect();
    let mut strides: Vec<u32> = vec![0; cards.len()];
    if !cards.is_empty() {
        strides[cards.len() - 1] = 1;
        for i in (0..cards.len() - 1).rev() {
            strides[i] = strides[i + 1] * cards[i + 1];
        }
    }

    let _ = writeln!(out, "        /// `{}`.", def.full_name);
    let _ = writeln!(
        out,
        "        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"
    );
    let _ = writeln!(out, "        pub struct {ty} {{");
    for p in &def.properties {
        let fname = rust_keyword_safe(&p.name);
        let fty = match &p.kind {
            PropKind::Bool => "bool".to_string(),
            PropKind::Int { .. } => "u8".to_string(),
            PropKind::Enum { enum_name, .. } => enum_name.clone(),
        };
        let _ = writeln!(out, "            pub {fname}: {fty},");
    }
    let _ = writeln!(out, "        }}");

    let _ = writeln!(out, "        impl {ty} {{");
    let _ = writeln!(
        out,
        "            pub const MIN_STATE_ID: i32 = {};",
        def.min_state_id
    );
    let _ = writeln!(
        out,
        "            pub const MAX_STATE_ID: i32 = {};",
        def.max_state_id
    );
    let _ = writeln!(
        out,
        "            pub const DEFAULT_STATE_ID: i32 = {};",
        def.default_state_id
    );

    // Default constant — derive property values from the default-state offset.
    let default_offset = (def.default_state_id - def.min_state_id) as u32;
    let _ = writeln!(out, "            pub const DEFAULT: Self = Self {{");
    let mut rem = default_offset;
    for (i, p) in def.properties.iter().enumerate() {
        let stride = strides[i];
        let idx = rem / stride;
        rem %= stride;
        let fname = rust_keyword_safe(&p.name);
        let val = match &p.kind {
            PropKind::Bool => match idx {
                0 => "true".to_string(),
                1 => "false".to_string(),
                _ => panic!("bool index out of range"),
            },
            PropKind::Int { .. } => format!("{idx}"),
            PropKind::Enum { enum_name, values } => {
                let v = pascal_case(&values[idx as usize]);
                format!("{enum_name}::{v}")
            }
        };
        let _ = writeln!(out, "                {fname}: {val},");
    }
    let _ = writeln!(out, "            }};");

    // to_state_id
    let _ = writeln!(
        out,
        "            #[inline] pub const fn to_state_id(self) -> i32 {{"
    );
    let _ = writeln!(out, "                Self::MIN_STATE_ID");
    for (i, p) in def.properties.iter().enumerate() {
        let stride = strides[i];
        let fname = rust_keyword_safe(&p.name);
        let expr = match &p.kind {
            PropKind::Bool => format!("(if self.{fname} {{ 0 }} else {{ 1 }})"),
            PropKind::Int { .. } => format!("(self.{fname} as i32)"),
            PropKind::Enum { .. } => format!("(self.{fname} as i32)"),
        };
        let _ = writeln!(out, "                    + {expr} * {stride}");
    }
    let _ = writeln!(out, "            }}");

    // from_state_id
    let _ = writeln!(
        out,
        "            #[inline] pub const fn from_state_id(id: i32) -> Option<Self> {{"
    );
    let _ = writeln!(
        out,
        "                if id < Self::MIN_STATE_ID || id > Self::MAX_STATE_ID {{ return None; }}"
    );
    let _ = writeln!(
        out,
        "                let mut rem = (id - Self::MIN_STATE_ID) as u32;"
    );
    // Walk fields in reverse to pull off the fastest-changing property first.
    for (i, p) in def.properties.iter().enumerate().rev() {
        let card = cards[i];
        let fname = rust_keyword_safe(&p.name);
        match &p.kind {
            PropKind::Bool => {
                let _ = writeln!(out, "                let {fname} = rem % {card} == 0;");
                let _ = writeln!(out, "                rem /= {card};");
            }
            PropKind::Int { .. } => {
                let _ = writeln!(out, "                let {fname} = (rem % {card}) as u8;");
                let _ = writeln!(out, "                rem /= {card};");
            }
            PropKind::Enum { enum_name, .. } => {
                let _ = writeln!(
                    out,
                    "                let {fname} = match {enum_name}::from_index(rem % {card}) {{ Some(v) => v, None => return None }};"
                );
                let _ = writeln!(out, "                rem /= {card};");
            }
        }
    }
    let _ = writeln!(out, "                let _ = rem;");
    let _ = writeln!(out, "                Some(Self {{");
    for p in &def.properties {
        let fname = rust_keyword_safe(&p.name);
        let _ = writeln!(out, "                    {fname},");
    }
    let _ = writeln!(out, "                }})");
    let _ = writeln!(out, "            }}");
    let _ = writeln!(out, "        }}");
}

fn emit_shapes_module(out: &mut String, defs: &[BlockDef], shapes_json: &Value) {
    // Build a deduplicated table of unique shape arrays.
    let shapes_obj = shapes_json
        .get("shapes")
        .and_then(|v| v.as_object())
        .expect("shapes.shapes object");

    // Deterministic order: numeric shape id ascending.
    let mut shape_ids: Vec<u32> = shapes_obj
        .keys()
        .map(|k| k.parse::<u32>().expect("numeric shape id"))
        .collect();
    shape_ids.sort_unstable();

    let _ = writeln!(
        out,
        "    /// Per-state collision shapes (axis-aligned boxes in [0,1]³)."
    );
    let _ = writeln!(out, "    pub mod shapes {{");
    let _ = writeln!(
        out,
        "        /// An axis-aligned box in block-local coordinates."
    );
    let _ = writeln!(out, "        #[derive(Debug, Clone, Copy, PartialEq)]");
    let _ = writeln!(out, "        pub struct Aabb {{");
    let _ = writeln!(out, "            pub x0: f32, pub y0: f32, pub z0: f32,");
    let _ = writeln!(out, "            pub x1: f32, pub y1: f32, pub z1: f32,");
    let _ = writeln!(out, "        }}");

    // Emit each shape as a static slice.
    let _ = writeln!(
        out,
        "        const FULL_CUBE: &[Aabb] = &[Aabb {{ x0:0.0,y0:0.0,z0:0.0,x1:1.0,y1:1.0,z1:1.0 }}];"
    );
    let _ = writeln!(out, "        const EMPTY: &[Aabb] = &[];");

    // Map shape_id -> static slice ident
    let mut shape_idents: BTreeMap<u32, String> = BTreeMap::new();
    for sid in &shape_ids {
        let arr = shapes_obj
            .get(&sid.to_string())
            .unwrap()
            .as_array()
            .unwrap();
        let ident = format!("SHAPE_{sid}");
        if arr.is_empty() {
            shape_idents.insert(*sid, "EMPTY".to_string());
            continue;
        }
        let _ = write!(out, "        const {ident}: &[Aabb] = &[");
        for (i, b) in arr.iter().enumerate() {
            if i > 0 {
                let _ = write!(out, ", ");
            }
            let nums: Vec<f32> = b
                .as_array()
                .unwrap()
                .iter()
                .map(|n| n.as_f64().unwrap() as f32)
                .collect();
            let _ = write!(
                out,
                "Aabb {{ x0:{:?},y0:{:?},z0:{:?},x1:{:?},y1:{:?},z1:{:?} }}",
                nums[0], nums[1], nums[2], nums[3], nums[4], nums[5]
            );
        }
        let _ = writeln!(out, "];");
        shape_idents.insert(*sid, ident);
    }

    // Emit per-state lookup as a single big `match`.
    let _ = writeln!(
        out,
        "        /// Returns the collision boxes for a block-state id."
    );
    let _ = writeln!(
        out,
        "        /// Falls back to `FULL_CUBE` for unknown ids and to `EMPTY`"
    );
    let _ = writeln!(out, "        /// for blocks the shape table doesn't cover.");
    let _ = writeln!(
        out,
        "        pub const fn for_state(state_id: i32) -> &'static [Aabb] {{"
    );
    let _ = writeln!(out, "            match state_id {{");
    for def in defs {
        if let Some(per_state) = &def.shape_per_state {
            // Group consecutive states sharing the same shape into ranges.
            let mut start = def.min_state_id;
            let mut prev_shape = per_state[0];
            for (offset, &cur) in per_state.iter().enumerate().skip(1) {
                if cur != prev_shape {
                    let end = def.min_state_id + offset as i32 - 1;
                    let ident = shape_idents
                        .get(&prev_shape)
                        .cloned()
                        .unwrap_or_else(|| "FULL_CUBE".to_string());
                    if start == end {
                        let _ = writeln!(out, "                {start} => {ident},");
                    } else {
                        let _ = writeln!(out, "                {start}..={end} => {ident},");
                    }
                    start = def.min_state_id + offset as i32;
                    prev_shape = cur;
                }
            }
            let end = def.min_state_id + per_state.len() as i32 - 1;
            let ident = shape_idents
                .get(&prev_shape)
                .cloned()
                .unwrap_or_else(|| "FULL_CUBE".to_string());
            if start == end {
                let _ = writeln!(out, "                {start} => {ident},");
            } else {
                let _ = writeln!(out, "                {start}..={end} => {ident},");
            }
        }
    }
    let _ = writeln!(out, "                _ => FULL_CUBE,");
    let _ = writeln!(out, "            }}");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
}

/// Returns the raw `values` array of a tag JSON, as strings (entry IDs or
/// `#tag` references). Object-form values (`{"id": ..., "required": ...}`)
/// are flattened to their `id` field.
fn parse_tag_values(value: &Value, path: &Path) -> Vec<String> {
    let arr = value
        .get("values")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("tag {} has no values array", path.display()));
    arr.iter()
        .map(|v| match v {
            Value::String(s) => s.clone(),
            Value::Object(o) => o
                .get("id")
                .and_then(|v| v.as_str())
                .unwrap_or_else(|| panic!("tag {} object value missing id", path.display()))
                .to_string(),
            _ => panic!("tag {} has non-string value: {v}", path.display()),
        })
        .collect()
}

/// Recursively resolves a tag's references. Returns a deduplicated, sorted
/// list of direct entry IDs.
fn resolve_tag(
    tag_id: &str,
    all_tags: &BTreeMap<String, Vec<String>>,
    seen: &mut HashSet<String>,
) -> Vec<String> {
    if !seen.insert(tag_id.to_string()) {
        return Vec::new();
    }
    let mut out: BTreeSet<String> = BTreeSet::new();
    if let Some(values) = all_tags.get(tag_id) {
        for v in values {
            if let Some(referenced) = v.strip_prefix('#') {
                for inner in resolve_tag(referenced, all_tags, seen) {
                    out.insert(inner);
                }
            } else {
                out.insert(v.clone());
            }
        }
    }
    seen.remove(tag_id);
    out.into_iter().collect()
}

/// Walks `dir` recursively and inserts (`relative-id-without-extension`, full path) into `out`.
fn collect_jsons(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    for entry in fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_jsons(root, &path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("json") {
            let rel = path.strip_prefix(root).unwrap().with_extension("");
            let id = rel.to_string_lossy().replace('\\', "/");
            out.insert(id, path);
        }
    }
}

// ---------------------------------------------------------------------------
// JSON → NBT conversion
// ---------------------------------------------------------------------------

#[derive(Clone)]
#[allow(dead_code)]
enum Hint {
    Auto,
    Byte,
    Int,
    Long,
    Float,
    Double,
    String,
    /// List with a single element-type hint applied to every element.
    List(Box<Hint>),
    /// Compound with sparse per-field overrides; unlisted fields use Auto.
    Compound(&'static [(&'static str, &'static Hint)]),
}

fn json_to_nbt(value: &Value, registry: &str) -> Nbt {
    let hint = root_hint(registry);
    let tag = convert(value, hint);
    let compound = match tag {
        Tag::Compound(c) => c,
        _ => panic!("registry {registry} root is not a compound"),
    };
    Nbt {
        name: Default::default(),
        compound,
    }
}

/// Per-registry root schema. Use `&Hint::Auto` for everything-heuristic.
fn root_hint(registry: &str) -> &'static Hint {
    match registry {
        "minecraft:dimension_type" => &DIMENSION_TYPE_HINT,
        _ => &Hint::Auto,
    }
}

// Sparse overrides: only fields where the heuristic is wrong (Double vs Float,
// Long vs Int) need to appear here.
//
// dimension_type 26.1.2 wraps most fields under `attributes.<namespaced_key>`
// (e.g. `attributes.minecraft:audio/ambient_sounds.mood.offset`).
static DT_MOOD: Hint = Hint::Compound(&[("offset", &Hint::Double)]);
static DT_AMBIENT_SOUNDS: Hint = Hint::Compound(&[("mood", &DT_MOOD)]);
static DT_ATTRIBUTES: Hint =
    Hint::Compound(&[("minecraft:audio/ambient_sounds", &DT_AMBIENT_SOUNDS)]);
static DIMENSION_TYPE_HINT: Hint = Hint::Compound(&[
    ("coordinate_scale", &Hint::Double),
    ("fixed_time", &Hint::Long),
    ("attributes", &DT_ATTRIBUTES),
]);

fn convert(value: &Value, hint: &Hint) -> Tag {
    match (hint, value) {
        (Hint::Auto, v) => convert_auto(v),

        (Hint::Byte, Value::Bool(b)) => Tag::Byte(if *b { 1 } else { 0 }),
        (Hint::Byte, Value::Number(n)) => Tag::Byte(n.as_i64().unwrap_or(0) as u8),

        (Hint::Int, Value::Number(n)) => Tag::Int(n.as_i64().unwrap_or(0) as i32),
        (Hint::Long, Value::Number(n)) => Tag::Long(n.as_i64().unwrap_or(0)),
        (Hint::Float, Value::Number(n)) => Tag::Float(n.as_f64().unwrap_or(0.0) as f32),
        (Hint::Double, Value::Number(n)) => Tag::Double(n.as_f64().unwrap_or(0.0)),

        (Hint::String, Value::String(s)) => Tag::String(s.clone().into()),

        (Hint::List(inner), Value::Array(arr)) => Tag::List(convert_list(arr, inner)),

        (Hint::Compound(fields), Value::Object(obj)) => {
            Tag::Compound(convert_compound(obj, fields))
        }

        _ => convert_auto(value),
    }
}

fn convert_auto(value: &Value) -> Tag {
    match value {
        Value::Bool(b) => Tag::Byte(if *b { 1 } else { 0 }),
        Value::Number(n) => {
            if n.is_i64() && !has_decimal(n) {
                let i = n.as_i64().unwrap();
                if (i32::MIN as i64..=i32::MAX as i64).contains(&i) {
                    Tag::Int(i as i32)
                } else {
                    Tag::Long(i)
                }
            } else {
                // Has decimal — default Float (most MC scalar fields are Float).
                Tag::Float(n.as_f64().unwrap_or(0.0) as f32)
            }
        }
        Value::String(s) => Tag::String(s.clone().into()),
        Value::Array(arr) => Tag::List(convert_list_auto(arr)),
        Value::Object(obj) => Tag::Compound(convert_compound_auto(obj)),
        Value::Null => Tag::Byte(0),
    }
}

fn has_decimal(n: &serde_json::Number) -> bool {
    !n.is_i64() && !n.is_u64()
}

fn convert_compound(obj: &Map<String, Value>, fields: &[(&str, &Hint)]) -> Compound {
    let tags = obj
        .iter()
        .map(|(k, v)| {
            let hint = fields
                .iter()
                .find(|(name, _)| *name == k)
                .map(|(_, h)| *h)
                .unwrap_or(&Hint::Auto);
            (k.clone().into(), convert(v, hint))
        })
        .collect();
    Compound { tags }
}

fn convert_compound_auto(obj: &Map<String, Value>) -> Compound {
    let tags = obj
        .iter()
        .map(|(k, v)| (k.clone().into(), convert_auto(v)))
        .collect();
    Compound { tags }
}

fn convert_list(arr: &[Value], inner: &Hint) -> List {
    if arr.is_empty() {
        return List::Empty;
    }
    let tags: Vec<Tag> = arr.iter().map(|v| convert(v, inner)).collect();
    pack_list(tags)
}

fn convert_list_auto(arr: &[Value]) -> List {
    if arr.is_empty() {
        return List::Empty;
    }
    let tags: Vec<Tag> = arr.iter().map(convert_auto).collect();
    pack_list(tags)
}

/// Group a homogeneous Vec<Tag> into the matching ussr-nbt List variant.
/// Falls back to List::Compound treating each element as a single-tag wrapper
/// only if all are compounds; otherwise panics with a clear message.
fn pack_list(tags: Vec<Tag>) -> List {
    let first = &tags[0];
    let kind = std::mem::discriminant(first);
    if tags.iter().any(|t| std::mem::discriminant(t) != kind) {
        panic!("heterogeneous NBT list — needs explicit Hint");
    }
    match first {
        Tag::Byte(_) => List::Byte(
            tags.into_iter()
                .map(|t| if let Tag::Byte(b) = t { b } else { 0 })
                .collect(),
        ),
        Tag::Short(_) => List::Short(
            tags.into_iter()
                .map(|t| if let Tag::Short(b) = t { b } else { 0 })
                .collect::<Vec<_>>()
                .into(),
        ),
        Tag::Int(_) => List::Int(
            tags.into_iter()
                .map(|t| if let Tag::Int(b) = t { b } else { 0 })
                .collect::<Vec<_>>()
                .into(),
        ),
        Tag::Long(_) => List::Long(
            tags.into_iter()
                .map(|t| if let Tag::Long(b) = t { b } else { 0 })
                .collect::<Vec<_>>()
                .into(),
        ),
        Tag::Float(_) => List::Float(
            tags.into_iter()
                .map(|t| if let Tag::Float(b) = t { b } else { 0.0 })
                .collect::<Vec<_>>()
                .into(),
        ),
        Tag::Double(_) => List::Double(
            tags.into_iter()
                .map(|t| if let Tag::Double(b) = t { b } else { 0.0 })
                .collect::<Vec<_>>()
                .into(),
        ),
        Tag::String(_) => List::String(
            tags.into_iter()
                .filter_map(|t| {
                    if let Tag::String(s) = t {
                        Some(s)
                    } else {
                        None
                    }
                })
                .collect(),
        ),
        Tag::List(_) => List::List(
            tags.into_iter()
                .filter_map(|t| if let Tag::List(l) = t { Some(l) } else { None })
                .collect(),
        ),
        Tag::Compound(_) => List::Compound(
            tags.into_iter()
                .filter_map(|t| {
                    if let Tag::Compound(c) = t {
                        Some(c)
                    } else {
                        None
                    }
                })
                .collect(),
        ),
        _ => panic!("unsupported list element type"),
    }
}
